language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install pep8
script:
  - pep8 --exclude=migrations magazine
  - ./magazine/example_project/manage.py test magazine
